/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator;

/**
 *
 * @author User
 */
public class MainJFrame extends javax.swing.JFrame {

    Calculator calc = new Calculator();
    boolean punctflag = false;//если мы уже поставили точку в числе типа double то второй раз уже поставить нельзя....
    double operandX = 0.0, operandY = 0.0;
    boolean isOperandX = false;
    boolean isOperandY = false;
    boolean lastSymbolWasOperator = false;
    char operator;
    boolean start = true;
    // boolean lastSymbolWasNumber=false;

    /**
     * Creates new form mainJFrame
     */
    public MainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBtn6 = new javax.swing.JButton();
        jBtn3 = new javax.swing.JButton();
        jBtnDiv = new javax.swing.JButton();
        jBtnPlus = new javax.swing.JButton();
        jBtnDot = new javax.swing.JButton();
        jBtn2 = new javax.swing.JButton();
        jBtnRezult = new javax.swing.JButton();
        jBtn9 = new javax.swing.JButton();
        jBtn0 = new javax.swing.JButton();
        jBtn8 = new javax.swing.JButton();
        jBtn4 = new javax.swing.JButton();
        jBtn5 = new javax.swing.JButton();
        jBtn1 = new javax.swing.JButton();
        jBtn7 = new javax.swing.JButton();
        jBtmMult = new javax.swing.JButton();
        jBtnDif = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Калькулятор");

        jBtn6.setText("6");
        jBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn6ActionPerformed(evt);
            }
        });

        jBtn3.setText("3");
        jBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn3ActionPerformed(evt);
            }
        });

        jBtnDiv.setText("/");
        jBtnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDivActionPerformed(evt);
            }
        });

        jBtnPlus.setText("+");
        jBtnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPlusActionPerformed(evt);
            }
        });

        jBtnDot.setText(".");
        jBtnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDotActionPerformed(evt);
            }
        });

        jBtn2.setText("2");
        jBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn2ActionPerformed(evt);
            }
        });

        jBtnRezult.setText("=");
        jBtnRezult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRezultActionPerformed(evt);
            }
        });

        jBtn9.setText("9");
        jBtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn9ActionPerformed(evt);
            }
        });

        jBtn0.setText("0");
        jBtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn0ActionPerformed(evt);
            }
        });

        jBtn8.setText("8");
        jBtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn8ActionPerformed(evt);
            }
        });

        jBtn4.setText("4");
        jBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn4ActionPerformed(evt);
            }
        });

        jBtn5.setText("5");
        jBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn5ActionPerformed(evt);
            }
        });

        jBtn1.setText("1");
        jBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn1ActionPerformed(evt);
            }
        });

        jBtn7.setText("7");
        jBtn7.setActionCommand("");
        jBtn7.setName("JBtn7"); // NOI18N
        jBtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn7ActionPerformed(evt);
            }
        });

        jBtmMult.setText("*");
        jBtmMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtmMultActionPerformed(evt);
            }
        });

        jBtnDif.setText("-");
        jBtnDif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDifActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setName(""); // NOI18N

        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setText("c");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField2.setBackground(new java.awt.Color(102, 102, 102));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBtn0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBtn4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBtn7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 1, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBtn8, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                    .addComponent(jBtn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBtnDot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBtn9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBtn6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBtn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBtnPlus, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBtnDiv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBtmMult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBtnRezult, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                    .addComponent(jBtnDif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField2)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtmMult, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnDif, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnDot, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnRezult, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn9ActionPerformed
        if (!lastSymbolWasOperator) {

            jTextField1.setText(jTextField1.getText() + '9'); //просто добавляем еще одну "3"

        } else {

            jTextField1.setText("");
            jTextField1.setText(jTextField1.getText() + '9'); //просто добавляем еще одну "3"

        }
        lastSymbolWasOperator = false;
    }//GEN-LAST:event_jBtn9ActionPerformed

    private void jBtnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDivActionPerformed

       char op='/';
       toPressOperator(op);
    }//GEN-LAST:event_jBtnDivActionPerformed

    private void jBtnDifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDifActionPerformed

      char op='-';
       toPressOperator(op);
    }//GEN-LAST:event_jBtnDifActionPerformed

    private void jBtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn7ActionPerformed
        char number='7';
     toPressNumber(number);
    }//GEN-LAST:event_jBtn7ActionPerformed

    private void jBtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn8ActionPerformed
       char number='8';
     toPressNumber(number);
    }//GEN-LAST:event_jBtn8ActionPerformed

    private void jBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn4ActionPerformed
       char number='4';
     toPressNumber(number);
    }//GEN-LAST:event_jBtn4ActionPerformed

    private void jBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn5ActionPerformed
        char number='5';
     toPressNumber(number);
    }//GEN-LAST:event_jBtn5ActionPerformed

    private void jBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn6ActionPerformed
        char number='6';
     toPressNumber(number);
    }//GEN-LAST:event_jBtn6ActionPerformed

    private void jBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn1ActionPerformed
       char number='1';
     toPressNumber(number);
    }//GEN-LAST:event_jBtn1ActionPerformed

    private void jBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn2ActionPerformed
        if (!lastSymbolWasOperator) {

            jTextField1.setText(jTextField1.getText() + '2'); //просто добавляем еще одну "3"

        } else {

            jTextField1.setText("");
            jTextField1.setText(jTextField1.getText() + '2'); //просто добавляем еще одну "3"

        }
        lastSymbolWasOperator = false;
    }//GEN-LAST:event_jBtn2ActionPerformed

   void toPressNumber(char number){

        if (!lastSymbolWasOperator) {

            jTextField1.setText(jTextField1.getText() + number); //просто добавляем еще одну "3"

        } else {

            jTextField1.setText("");
            jTextField1.setText(jTextField1.getText() + number); //просто добавляем еще одну "3"

        }
        lastSymbolWasOperator = false;
    }
    
    private void jBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn3ActionPerformed
char number='3';
     toPressNumber(number);
    }//GEN-LAST:event_jBtn3ActionPerformed


    private void jBtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn0ActionPerformed
        char number='0';
     toPressNumber(number);
    }//GEN-LAST:event_jBtn0ActionPerformed

    private void jBtnRezultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRezultActionPerformed
       if(operator=='='){
           operator = '=';
       
       return;     
       }
        if ((isOperandX) && (!isOperandY)) {
            operandY = Double.parseDouble(jTextField1.getText());

            jTextField2.setText("");
            jTextField1.setText(Double.toString(calc.toCalculate(operator, operandX, operandY)));
            operandX = calc.toCalculate(operator, operandX, operandY);
            operandX=0;
            operandY=0;
            operator = '=';
            isOperandY=false;
            isOperandX=true;
        }

//        
//        jTextField1.setText(Double.toString(calc.toCalculate(operator,operandX, operandY)));
//        
//        punctflag = false;//если мы уже поставили точку в числе типа double то второй раз уже поставить нельзя....
//        operandX = 0.0;
//        operandY = 0.0;
//        isOperandX = false;
//        isOperandY = false;
//        lastSymbolWasOperator = false;
//        start=true;
//    
//       // jTextField1.setText("");
//        jTextField2.setText("");
//        

    }//GEN-LAST:event_jBtnRezultActionPerformed

    Boolean textFieldIsEmpty(StringBuilder tempStr) {
        boolean isEmpty;
        isEmpty = tempStr.length() == 0;
        return isEmpty;
    }

    void changeOperator(char operator, StringBuilder tempStr) {

        switch (operator) {

            case '+': {
                if ((tempStr.charAt(tempStr.length() - 1) == '+') || (tempStr.charAt(tempStr.length() - 1) == '*') || (tempStr.charAt(tempStr.length() - 1) == '/') || (tempStr.charAt(tempStr.length() - 1) == '-')) {
                    tempStr.setCharAt(tempStr.length() - 1, '+');
                    jTextField2.setText(jTextField2.getText() + tempStr.toString());
                } else {
                    jTextField2.setText(jTextField2.getText() + operator);
                }
                break;
            }
            case '-': {
                if ((tempStr.charAt(tempStr.length() - 1) == '+') || (tempStr.charAt(tempStr.length() - 1) == '*') || (tempStr.charAt(tempStr.length() - 1) == '/') || (tempStr.charAt(tempStr.length() - 1) == '-')) {
                    tempStr.setCharAt(tempStr.length() - 1, '-');
                    jTextField1.setText(tempStr.toString());
                } else {
                    jTextField1.setText(jTextField1.getText() + operator);
                }
                break;
            }

            case '*': {
                if ((tempStr.charAt(tempStr.length() - 1) == '+') || (tempStr.charAt(tempStr.length() - 1) == '*') || (tempStr.charAt(tempStr.length() - 1) == '/') || (tempStr.charAt(tempStr.length() - 1) == '-')) {
                    tempStr.setCharAt(tempStr.length() - 1, '*');
                    jTextField1.setText(tempStr.toString());
                } else {
                    jTextField1.setText(jTextField1.getText() + operator);
                }
                break;
            }

            case '/': {
                if ((tempStr.charAt(tempStr.length() - 1) == '+') || (tempStr.charAt(tempStr.length() - 1) == '*') || (tempStr.charAt(tempStr.length() - 1) == '/') || (tempStr.charAt(tempStr.length() - 1) == '-')) {
                    tempStr.setCharAt(tempStr.length() - 1, '/');
                    jTextField1.setText(tempStr.toString());
                } else {
                    jTextField1.setText(jTextField1.getText() + operator);
                }
                break;
            }

        }

    }

    void copyValueToTextField2(char operator) {
        jTextField2.setText(jTextField2.getText() + jTextField1.getText() + operator);
    }

  void  toPressOperator(char pressedOperator){
    char op = pressedOperator;
        if (lastSymbolWasOperator) return;
        if (jTextField1.getText().length() == 0) return;
        punctflag = false;

        if (operator == '=') {
             operandX = Double.parseDouble(jTextField1.getText());
            jTextField2.setText(jTextField1.getText()+op);
            lastSymbolWasOperator=true;
            isOperandY=false;
            isOperandX=true;
            operator=pressedOperator;
            return;
        }
        //если x пустой то кидаем в него значение введеное
        if (isOperandX == false) {
            operandX = Double.parseDouble(jTextField1.getText());
            //теперь у нас есть первое значение
            isOperandX = true;
            //установим флаг что был нажат оператор 
            lastSymbolWasOperator = true;
            //копируем то что внизу наверх
            copyValueToTextField2(op);
            operator = pressedOperator;
            //выходим из метода

        } // если первое значение  isOperandX у нас заполенно то мы должны кинуть значение в y
        else if ((isOperandX) && (!isOperandY)) {
            operandY = Double.parseDouble(jTextField1.getText());
            lastSymbolWasOperator = true;
            //копируем то что внизу наверх
            copyValueToTextField2(op);
            //проверим если до этого было '=' то заменяем на '+'
           

            jTextField1.setText(Double.toString(calc.toCalculate(operator, operandX, operandY)));
            operandX = calc.toCalculate(operator, operandX, operandY);
            lastSymbolWasOperator = true;
            operator = pressedOperator;
        }

    }
    private void jBtnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPlusActionPerformed
char op='+';
       toPressOperator(op);
    }//GEN-LAST:event_jBtnPlusActionPerformed

    private void jBtmMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtmMultActionPerformed

       char op='*';
       toPressOperator(op);
    }//GEN-LAST:event_jBtmMultActionPerformed

    private void jBtnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDotActionPerformed
        String tempStr = jTextField1.getText();
        char ch;
        if (!tempStr.isEmpty()) {
            ch = tempStr.charAt(tempStr.length() - 1);

        } else {
            return;
        }

        if ((ch != '+') && (ch != '-') && (ch != '*') && (ch != '/')) {
            if (punctflag == false) {
                jTextField1.setText(jTextField1.getText() + '.');
            }
            punctflag = true;
        }


    }//GEN-LAST:event_jBtnDotActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        punctflag = false;//если мы уже поставили точку в числе типа double то второй раз уже поставить нельзя....
        operandX = 0.0;
        operandY = 0.0;
        isOperandX = false;
        isOperandY = false;
        lastSymbolWasOperator = false;

        jTextField1.setText("");
        jTextField2.setText("");

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtmMult;
    private javax.swing.JButton jBtn0;
    private javax.swing.JButton jBtn1;
    private javax.swing.JButton jBtn2;
    private javax.swing.JButton jBtn3;
    private javax.swing.JButton jBtn4;
    private javax.swing.JButton jBtn5;
    private javax.swing.JButton jBtn6;
    private javax.swing.JButton jBtn7;
    private javax.swing.JButton jBtn8;
    private javax.swing.JButton jBtn9;
    private javax.swing.JButton jBtnDif;
    private javax.swing.JButton jBtnDiv;
    private javax.swing.JButton jBtnDot;
    private javax.swing.JButton jBtnPlus;
    private javax.swing.JButton jBtnRezult;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
